name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  http: ^0.13.5
  firebase_auth: ^4.3.0
  provider: ^6.0.5
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  flutter_jap_icons: ^0.2.1
  image_picker: ^0.8.7+1
  flutter_barcode_scanner: ^2.0.0
  collection: ^1.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
